/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components' | '/foundations' | '/marketing' | '/social'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/foundations' | '/marketing' | '/social'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/foundations'
    | '/marketing'
    | '/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  FoundationsRoute: typeof FoundationsRoute
  MarketingRoute: typeof MarketingRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  FoundationsRoute: FoundationsRoute,
  MarketingRoute: MarketingRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
