/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as IconographyRouteImport } from './routes/iconography'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminKnowledgeBaseRouteImport } from './routes/_authenticated/admin.knowledge-base'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const IconographyRoute = IconographyRouteImport.update({
  id: '/iconography',
  path: '/iconography',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminKnowledgeBaseRoute =
  AuthenticatedAdminKnowledgeBaseRouteImport.update({
    id: '/admin/knowledge-base',
    path: '/admin/knowledge-base',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
  '/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
  '/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/foundations': typeof FoundationsRoute
  '/iconography': typeof IconographyRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/marketing': typeof MarketingRoute
  '/social': typeof SocialRoute
  '/_authenticated/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/components'
    | '/contact'
    | '/downloads'
    | '/foundations'
    | '/iconography'
    | '/knowledge-base'
    | '/marketing'
    | '/social'
    | '/admin/knowledge-base'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/components'
    | '/contact'
    | '/downloads'
    | '/foundations'
    | '/iconography'
    | '/knowledge-base'
    | '/marketing'
    | '/social'
    | '/admin/knowledge-base'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/components'
    | '/contact'
    | '/downloads'
    | '/foundations'
    | '/iconography'
    | '/knowledge-base'
    | '/marketing'
    | '/social'
    | '/_authenticated/admin/knowledge-base'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComponentsRoute: typeof ComponentsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FoundationsRoute: typeof FoundationsRoute
  IconographyRoute: typeof IconographyRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  MarketingRoute: typeof MarketingRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iconography': {
      id: '/iconography'
      path: '/iconography'
      fullPath: '/iconography'
      preLoaderRoute: typeof IconographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/knowledge-base': {
      id: '/_authenticated/admin/knowledge-base'
      path: '/admin/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminKnowledgeBaseRoute: typeof AuthenticatedAdminKnowledgeBaseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminKnowledgeBaseRoute: AuthenticatedAdminKnowledgeBaseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComponentsRoute: ComponentsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FoundationsRoute: FoundationsRoute,
  IconographyRoute: IconographyRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  MarketingRoute: MarketingRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
